Repository entando-k8s/entando-k8s-custom-model, pull requests merged in 2020-10, with the labels that each got.

#31 Eng 1266 git ssh secret
  pom.xml
  src/main/java/org/entando/kubernetes/model/app/EntandoAppSpec.java
  src/main/java/org/entando/kubernetes/model/app/EntandoAppSpecFluent.java
  src/main/resources/crd/EntandoAppCRD.yaml
  src/main/resources/crd/EntandoClusterInfrastructureCRD.yaml
  src/main/resources/crd/EntandoDatabaseServiceCRD.yaml
  src/main/resources/crd/EntandoKeycloakServerCRD.yaml
  src/main/resources/crd/EntandoPluginCRD.yaml
  src/test/java/org/entando/kubernetes/model/AbstractEntandoAppTest.java
Labels: approved, size/M

#30 ENG-1301 removed overly strict regexp for ingressHostname
  src/main/resources/crd/EntandoAppCRD.yaml
  src/main/resources/crd/EntandoClusterInfrastructureCRD.yaml
  src/main/resources/crd/EntandoDatabaseServiceCRD.yaml
  src/main/resources/crd/EntandoKeycloakServerCRD.yaml
  src/main/resources/crd/EntandoPluginCRD.yaml
Labels: size/S

#32 Update OWNERS
  OWNERS
Labels: approved, size/XS

#34 ENG-1329 introduced support for the old style parameters for compatibility
  pom.xml
  src/main/java/org/entando/kubernetes/model/EntandoDeploymentSpec.java
  src/main/java/org/entando/kubernetes/model/EntandoDeploymentSpecBuilder.java
  src/main/java/org/entando/kubernetes/model/app/EntandoAppSpec.java
  src/main/java/org/entando/kubernetes/model/app/EntandoAppSpecFluent.java
  src/main/java/org/entando/kubernetes/model/externaldatabase/EntandoDatabaseServiceSpec.java
  src/main/java/org/entando/kubernetes/model/externaldatabase/EntandoDatabaseServiceSpecFluent.java
  src/main/java/org/entando/kubernetes/model/infrastructure/EntandoClusterInfrastructureSpec.java
  src/main/java/org/entando/kubernetes/model/infrastructure/EntandoClusterInfrastructureSpecFluent.java
  src/main/java/org/entando/kubernetes/model/keycloakserver/EntandoKeycloakServerSpec.java
  src/main/java/org/entando/kubernetes/model/keycloakserver/EntandoKeycloakServerSpecFluent.java
  src/main/java/org/entando/kubernetes/model/plugin/EntandoPluginSpec.java
  src/main/java/org/entando/kubernetes/model/plugin/EntandoPluginSpecFluent.java
  src/main/resources/crd/EntandoAppCRD.yaml
  src/main/resources/crd/EntandoClusterInfrastructureCRD.yaml
  src/main/resources/crd/EntandoDatabaseServiceCRD.yaml
  src/main/resources/crd/EntandoKeycloakServerCRD.yaml
  src/main/resources/crd/EntandoPluginCRD.yaml
  src/main/resources/crd/examples/plugin-with-embedded-postgresql-db.yml
  src/main/resources/crd/examples/plugin-with-external-postgresql-db.yml
  src/test/java/org/entando/kubernetes/model/AbstractEntandoAppTest.java
  src/test/java/org/entando/kubernetes/model/AbstractEntandoDatabaseServiceTest.java
  src/test/java/org/entando/kubernetes/model/AbstractEntandoPluginTest.java
  src/test/java/org/entando/kubernetes/model/CustomResourceTestUtil.java
  src/test/java/org/entando/kubernetes/model/inprocesstest/EntandoAppMockedTest.java
  src/test/java/org/entando/kubernetes/model/inprocesstest/EntandoAppPluginLinkMockedTest.java
  src/test/java/org/entando/kubernetes/model/inprocesstest/EntandoClusterInfrastructureMockedTest.java
  src/test/java/org/entando/kubernetes/model/inprocesstest/EntandoCompositeAppMockedTest.java
  src/test/java/org/entando/kubernetes/model/inprocesstest/EntandoCustomResourceStatusTest.java
  src/test/java/org/entando/kubernetes/model/inprocesstest/EntandoDatabaseServiceMockedTest.java
  src/test/java/org/entando/kubernetes/model/inprocesstest/EntandoDeBundleMockedTest.java
  src/test/java/org/entando/kubernetes/model/inprocesstest/EntandoKeycloakServerMockedTest.java
  src/test/java/org/entando/kubernetes/model/inprocesstest/EntandoPluginMockedTest.java
  src/test/java/org/entando/kubernetes/model/interprocesstest/EntandoAppIntegratedTest.java
  src/test/java/org/entando/kubernetes/model/interprocesstest/EntandoAppPluginLinkIntegratedTest.java
  src/test/java/org/entando/kubernetes/model/interprocesstest/EntandoClusterInfrastructureIntegratedTest.java
  src/test/java/org/entando/kubernetes/model/interprocesstest/EntandoCompositeAppIntegratedTest.java
  src/test/java/org/entando/kubernetes/model/interprocesstest/EntandoDatabaseServiceIntegratedTest.java
  src/test/java/org/entando/kubernetes/model/interprocesstest/EntandoDeBundleIntegratedTest.java
  src/test/java/org/entando/kubernetes/model/interprocesstest/EntandoKeycloakServerIntegratedTest.java
  src/test/java/org/entando/kubernetes/model/interprocesstest/EntandoPluginIntegratedTest.java
Labels: approved, size/L
