Repository entando-k8s/entando-k8s-custom-model, pull requests merged in 2022-01, with the labels that each got.

#47 ENG-3133 fix CRD openAPIV3Schema.type field
  pom.xml
  src/main/resources/crd/entandoapppluginlinks.entando.org.crd.yaml
  src/main/resources/crd/entandoapps.entando.org.crd.yaml
  src/main/resources/crd/entandocompositeapps.entando.org.crd.yaml
  src/main/resources/crd/entandodatabaseservices.entando.org.crd.yaml
  src/main/resources/crd/entandodebundles.entando.org.crd.yaml
  src/main/resources/crd/entandokeycloakservers.entando.org.crd.yaml
  src/main/resources/crd/entandoplugins.entando.org.crd.yaml
  src/main/resources/crd/providedcapabilities.entando.org.crd.yaml
Labels: approved, size/S

#46 ENG-3007 Updating parent version
  .snyk
  pom.xml
Labels: size/M, approved

#48 ENG-3175 Updating parent version
  .snyk
  owasp-dependency-check-suppression.xml
  pom.xml
Labels: size/L, approved
